services:
  - type: web
    name: best-cars-dealership
    env: python
    rootDir: server
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
